List friendsList = [
  'Alice Doe',
  'Bob Smith',
  'Charlie Brown',
  'David Johnson',
  'Eve Williams',
  'Frank Wilson',
  'Grace Lee',
  'Henry Davis',
  'Ivy Martinez',
  'Jack Taylor',
  'Kate Anderson',
  'Liam Thomas',
  'Michael Garcia',
  'Natalie Rodriguez',
  'Oliver Hernandez',
  'Penelope Martinez',
  'Quinn Lopez',
  'Rachel Perez',
  'Samuel Gonzalez',
  'Tara Flores',
  'Uma Patel',
  'Victor Ramirez'
];
